# Generated by Django 5.1.1 on 2024-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/kojo_pic/'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
