# Generated by Django 5.1.1 on 2024-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_post_image_remove_post_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description about yourself (up to 500 characters).', max_length=500, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City where you currently reside.', max_length=100, null=True, verbose_name='City of Residence'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Select your gender.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('in_a_relationship', 'In a Relationship'), ('married', 'Married'), ('complicated', 'It’s Complicated')], help_text='Select your current relationship status.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studied_at',
            field=models.CharField(blank=True, help_text='Where did you study?', max_length=100, null=True, verbose_name='Education'),
        ),
    ]
